config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("truck.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

truck/urls.py
from django.urls import include, path

from truck.views import CalcUnloadView, TruckListView

app_name = "truck"

urlpatterns = [
    path("", TruckListView.as_view(), name="trip_truck_calc_list"),
    path("calc/", CalcUnloadView.as_view(), name="calc_unload"),
]

warehouse/models.py
from django.contrib.gis.db import models


class Warehouse(models.Model):
    name = models.CharField(
        verbose_name="Название",
        max_length=255,
    )
    area = models.PolygonField(
        verbose_name="Область склада",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Склад"
        verbose_name_plural = "Склады"


class WarehouseMoveMineralEventAbs(models.Model):
    """
    Общая модель событий загрузки-выгрузки со склада
    """

    datetime = models.DateTimeField(
        "Время события",
        auto_now_add=True,
    )
    extraction_point = models.ForeignKey(
        "extraction_point.ExtractionPoint",
        verbose_name="Откуда привезли",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    trip_truck = models.ForeignKey(
        "truck.TripTruck",
        verbose_name="Грузовик совершивший действие",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    total_tons = models.FloatField("Масса всей выгрузки")
    si_o_2_tons = models.FloatField("Масса диоксида кремния")
    fe_tons = models.FloatField("Масса железа")

    class Meta:
        abstract = True


class WarehouseMoveMineralEvent(WarehouseMoveMineralEventAbs):
    """
    Модель событий загрузки-выгрузки со склада
    """

    warehouse = models.ForeignKey(
        Warehouse,
        verbose_name="Склад",
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = "Движение по складу"


class OutsideWarehouseMoveMineralEvent(WarehouseMoveMineralEventAbs):
    """
    Модель событий выгрузки мимо склада. Логичнее вынести
    в отдельную сущность так как вероятно в основных процессах
    она учавствовать не будет и данные записи будут создавать
    неудобства в работе
    """

    class Meta:
        verbose_name = "Отвалы промахи вокруг склада"

warehouse/templates/calc_unload_table.html
{% extends "base.html" %}

{% block main %}
<h2>Изменения на складах затронутых тестовой выгрузкой</h2>
{% if warehouse_list%}
    <table>
        <tr>
            <th>Название склада</th>
            <th>Обьем до загрузки, т</th>
            <th>Обьем после загрузки, т</th>
            <th>Качественные хар-ки после загрузки</th>
        </tr>
        {% for w in warehouse_list %}
            <tr>
                <td>{{w.name}}</td>
                <td>{{w.weight_tons_pre_upload}}</td>
                <td>{{w.weight_tons}}</td>
                <td>{{w.minerals_info}}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h4>Все выгрузки произошли мимо складов</h4>
{% endif %}
<br>
<a href="{% url 'truck:trip_truck_calc_list' %}">Вернуться</a>
{% endblock main %}

warehouse/templates/form.html
{% extends "base.html" %}

{% block main %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form.management_form }}
    <table>
    {% for i in form %}
        {% if forloop.first %}
            <tr>
                {% for ii in i.visible_fields %}
                    <th>
                    {{ii.label}}
                    </th>
                {% endfor %}
            </tr>
        {% endif %}
        <tr>
            {% for ii in i.visible_fields %}
                <td>
                {% if ii.field.disabled is True %}
                    {{ii.value}}
                {% else %}
                    {{ii}}
                    {{ii.errors}}
                {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </table>
    {% for i in form %}
        {% for ii in i.hidden_fields %}
            {{ii}}
        {% endfor %}
    {% endfor %}

    <br>
    <input type="submit" value="Рассчитать">
</form>
{% endblock main %}